### ISSUE TITLE
setExtraClasspath  is removed when running with Java 11 or above.

### ISSUE THREAD

**Issue by FuqiangWang** [vert-x3/vertx-maven-service-factory#38]
### Questions

setExtraClasspath  is removed when running with Java 11 or above.

Running with Java 11. 
java.lang.NoSuchMethodError: 'io.vertx.core.DeploymentOptions io.vertx.core.DeploymentOptions.setExtraClasspath(java.util.List)'

### Version

4.3.1

### Context

Running with Java 11. 

java.lang.NoSuchMethodError: 'io.vertx.core.DeploymentOptions io.vertx.core.DeploymentOptions.setExtraClasspath(java.util.List)'
	at io.vertx.maven.MavenVerticleFactory.lambda$createVerticle$1(MavenVerticleFactory.java:160)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:101)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)

### Extra

openjdk version "11.0.7" 2020-04-14

**Comment by vietj** [comment]
yes that's expected, this became unsupported with Java 11
